"""Data models for the Producer system."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from pathlib import Path


MAX_EXCHANGES_PER_SEGMENT = 10  # cap on voice_cues per segment (multi-host dialogue)


@dataclass
class CharacterConfig:
    """Character personality loaded from YAML — pure data, no behavior."""

    id: str
    name: str
    personality: str
    voice_speaker: str = "Aiden"
    voice_instruct: str = "Speak naturally"
    genre_weights: dict[str, float] = field(default_factory=dict)
    avoid_genres: set[str] = field(default_factory=set)


@dataclass
class VoiceCue:
    """One voice line in a script segment."""

    character_id: str
    style: str  # intro | outro | mid_song | between_songs | bridge | silent
    text: str
    tts_audio: Path | None = None
    tts_duration: float = 0.0


@dataclass
class ScriptSegment:
    """One segment: a song + zero or more voice cues."""

    position: int
    track: dict  # Library track dict (file_path, artist, title, genre, etc.)
    voice_cues: list[VoiceCue] = field(default_factory=list)
    state: str = "planned"  # planned | materializing | ready | playing | done
    served: bool = False  # True once select_next has handed this segment to the planner


@dataclass
class Script:
    """A rolling content plan generated by the Producer."""

    segments: list[ScriptSegment] = field(default_factory=list)
    cursor: int = 0
    primary_character: str = ""
    cast: list[str] = field(default_factory=list)  # all character IDs active in this script
    generated_at: float = field(default_factory=time.time)

    @property
    def current(self) -> ScriptSegment | None:
        if 0 <= self.cursor < len(self.segments):
            return self.segments[self.cursor]
        return None

    @property
    def remaining(self) -> list[ScriptSegment]:
        return [s for s in self.segments[self.cursor:] if s.state != "done"]

    def advance(self) -> ScriptSegment | None:
        if self.cursor < len(self.segments) - 1:
            self.cursor += 1
            return self.current
        return None


@dataclass
class SeedState:
    """A sticky seed that drives show generation until replaced.

    Produced by the seed interpreter from any of: text, song, character,
    cast, genre, image. Consumed by script building (first_song, cast,
    genre_focus, mood_text) and surfaced via /api/producer/status.
    """

    raw: dict = field(default_factory=dict)           # original request body
    set_at: float = field(default_factory=time.time)  # epoch seconds
    pipeline: str = "character"                       # song|character|genre|vibe|duo|artist|image
    cast: list[str] = field(default_factory=list)     # character IDs active for this seed
    first_song: dict | None = None                    # library track dict if seeded by a song
    genre_focus: list[str] = field(default_factory=list)  # genres to weight up
    mood_text: str | None = None                      # natural-language mood hint for LLM
    interpretation_notes: str = ""                    # human-readable one-liner for /status
    uploaded_image_path: str | None = None            # resolved path if image upload/url
    strict: bool = False                              # hard-filter songs to genre_focus matches
    hard: bool = False                                # skip current track once new first song is queued
    hard_consumed: bool = False                       # that one-shot skip has already fired
    built_at: float | None = None                     # epoch when new script finished building
    songs_queued_at: float | None = None              # epoch when new tracks were pushed to LS (phase 1)
    live_at: float | None = None                      # epoch when first new-script track hit air

    def as_dict(self) -> dict:
        """JSON-friendly shape for API responses."""
        build_seconds = (
            round(self.built_at - self.set_at, 2)
            if self.built_at else None
        )
        total_handover_seconds = (
            round(self.live_at - self.set_at, 2)
            if self.live_at else None
        )
        return {
            "pipeline": self.pipeline,
            "cast": list(self.cast),
            "first_song": {
                "artist": self.first_song.get("artist", "?"),
                "title": self.first_song.get("title", "?"),
                "file_path": self.first_song.get("file_path", ""),
            } if self.first_song else None,
            "genre_focus": list(self.genre_focus),
            "mood_text": self.mood_text,
            "interpretation_notes": self.interpretation_notes,
            "uploaded_image_path": self.uploaded_image_path,
            "strict": self.strict,
            # `hard` stays the value that was requested; `hard_consumed` says
            # whether the one-shot skip has already fired, so a live seed never
            # looks like it still has a pending cut.
            "hard": self.hard,
            "hard_consumed": self.hard_consumed,
            "timing": {
                "set_at": self.set_at,
                "songs_queued_at": self.songs_queued_at,
                "built_at": self.built_at,
                "live_at": self.live_at,
                "songs_queued_seconds": (
                    round(self.songs_queued_at - self.set_at, 2)
                    if self.songs_queued_at else None
                ),
                "build_seconds": build_seconds,
                "total_handover_seconds": total_handover_seconds,
            },
            "raw": {k: v for k, v in self.raw.items() if k != "image"},
        }
